version: 2

refrences:

  cache-options: &cache-options
    key: package-cache-{{ checksum "package.json" }}

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: npm-install
          command: npm install
      - run:
          name: test-reporter-setup
          command: npm install jest-junit --no-save
      - save_cache:
          <<: *cache-options
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: linter
          command: ./node_modules/.bin/standard
      - run:
          name: test-reporter-setup
          command: mkdir ./junit
      - run:
          name: test
          command: ./node_modules/.bin/jest --ci --testResultsProcessor="jest-junit" --runInBand
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/jest.xml
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
